AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket for Patch Override List
Resources:
  PatchOverrideListBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: ct-patch-override-list

Outputs:
  BucketName:
    Value: !Ref PatchOverrideListBucket
    Description: Name of the S3 bucket
