# Controls when the action will run. Invokes the workflow on push events but only for the main branch
name: Deployment at Sandbox 1
on:
    push:
      branches: [ main ]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
  
  # Permission can be added at job level or workflow level    
permissions:
        id-token: write   # This is required for requesting the JWT
        contents: read    # This is required for actions/checkout
  
jobs:
    SandboxDeployment:
      runs-on: ubuntu-latest
      environment: sandbox-1
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: ${{ secrets.AWS_ROLE }} #Declare at Repository secret
            role-session-name: GitHub_Action
            aws-region: ${{ secrets.AWS_REGION }} #Declare at Repository secret
        
        - name: Deploy Patch Override List
          uses: aws-actions/aws-cloudformation-github-deploy@v1
          with:
            name: SSM-Patch-Override-List
            template: SSM-Automation-OverrideList.yaml
            no-fail-on-empty-changeset: "1"
            capabilities: CAPABILITY_NAMED_IAM

        - name: Copy Patch Override File with the AWS CLI
          run: |
            aws s3 cp patch-override-list/Q1-2024.yml s3://ct-patch-override-list

        - name: Deploy to AWS organization
          uses: aws-actions/aws-cloudformation-github-deploy@v1
          with:
            name: SSM-Patch-Canary-Group-1-Scan
            template: SSM-Automation-Management.yaml
            no-fail-on-empty-changeset: "1"
            capabilities: CAPABILITY_NAMED_IAM
            parameter-overrides: >-
               TaskName=DailyScan,
               EventBridgeRuleSchedule=cron(0/10 * * * ? *),
               ExecutionRoleName=AWS-SystemsManager-AutomationExecutionRole,
               ExistingAutomationAdministrationRole='',
               MaximumConcurrency=10%,
               MaximumErrors=10%,
               RunPatchBaselineOperation=Scan,
               RunPatchBaselineRebootOption=NoReboot,
               RunPatchBaselineInstallOverrideList='',
               ResourceGroupName=canary-1,
               TargetAccounts=186638637306,
               TargetLocationMaxConcurrency=1,
               TargetLocationMaxErrors=1,
               TargetRegionIds=ap-southeast-2

        - name: Deploy to AWS organization - Install
          uses: aws-actions/aws-cloudformation-github-deploy@v1
          with:
            name: SSM-Patch-Canary-Group-1-Install
            template: SSM-Automation-Management.yaml
            no-fail-on-empty-changeset: "1"
            capabilities: CAPABILITY_NAMED_IAM
            parameter-overrides: >-
               TaskName=DailyInstall,
               EventBridgeRuleSchedule=cron(0/10 * * * ? *),
               ExecutionRoleName='',
               ExistingAutomationAdministrationRole=AWS-SystemsManager-AutomationExecutionRole,
               MaximumConcurrency=10%,
               MaximumErrors=10%,
               RunPatchBaselineOperation=Install,
               RunPatchBaselineRebootOption=NoReboot,
               RunPatchBaselineInstallOverrideList='',
               ResourceGroupName=canary-1,
               TargetAccounts=186638637306,
               TargetLocationMaxConcurrency=1,
               TargetLocationMaxErrors=1,
               TargetRegionIds=ap-southeast-2          
